-- Inserir 56 novos cursos na tabela new_courses
INSERT INTO public.new_courses (curso, status, professor, user_id) VALUES
('Paternidade Responsável', 'Atualizando', 'Lucas', NULL),
('Sistemas Adaptativos, Ensino Híbrido e Metodologias Ativas', 'Novo', 'Eliane', NULL),
('Sistema Financeiro Nacional', 'Novo', 'Lucas', NULL),
('Recrutamento e Seleção de Pessoal', 'Atualizar', 'Lucas', NULL),
('Sistemas Operacionais', 'Atualizar', 'Lucas', NULL),
('Crédito e Cobrança', 'Atualizar', 'Lucas', NULL),
('Psicologia Escolar e Educacional', 'Atualizando', 'Eliane', NULL),
('Psicologia do Desenvolvimento', 'Atualizar', 'Eliane', NULL),
('Fundamentos de enfermagem', 'Novo', 'Lucas', NULL),
('Design Gráfico', 'Atualizar', 'Lucas', NULL),
('Comportamento do Consumidor', 'Atualizar', 'Eliane', NULL),
('Marketing de Serviços', 'Atualizar', 'Eliane', NULL),
('Criminologia', 'Atualizar', 'Eliane', NULL),
('Plano Educacional Individualizado (PEI)', 'Atualizar', 'Eliane', NULL),
('Operador de Computador', 'Atualizar', 'Lucas', NULL),
('Auxiliar de Veterinário e Pet Shop', 'Atualizar', 'Lucas', NULL),
('Mecânica Industrial', 'Atualizar', 'Lucas', NULL),
('Unidade de Alimentação e Nutrição - UAN', 'Atualizar', 'Eliane', NULL),
('Construção de Ambientes Virtuais', 'Novo', 'Eliane', NULL),
('Mídias Digitais e Educação Inclusiva', 'Novo', 'Eliane', NULL),
('Tecnologias Assistivas', 'Novo', 'Eliane', NULL),
('Softwares Educacionais Livres', 'Novo', 'Eliane', NULL),
('Tutoria EAD', 'Novo', 'Eliane', NULL),
('Ferramentas Digitais na Educação', 'Novo', 'Eliane', NULL),
('Gamificação e Educação', 'Novo', 'Eliane', NULL),
('Segurança do Trabalho', 'Atualizar', 'Eliane', NULL),
('Técnico em Marketing', 'Novo', 'Eliane', NULL),
('CFTV', 'Atualizar', 'Lucas', NULL),
('Licitações e Contratos (nova Lei de Licitações)', 'Atualizar', 'Lucas', NULL),
('LEI DE RESPONSABILIDADE FISCAL - LRF(LEI N° 101/2000)', 'Atualizando', 'Lucas', NULL),
('Economia Aplicada', 'Novo', 'Lucas', NULL),
('Responsabilidade Social e Ambiental das Empresas', 'Novo', 'Eliane', NULL),
('Código de Defesa do Consumidor', 'Novo', 'Eliane', NULL),
('Lei de Proteção de Dados', 'Novo', 'Eliane', NULL),
('Lei Maria da Penha', 'Novo', 'Eliane', NULL),
('Lei de Improbidade Administrativa', 'Novo', 'Eliane', NULL),
('Agência de Viagens e Turismo', 'Novo', 'Eliane', NULL),
('Turismo e Hotelaria', 'Novo', 'Eliane', NULL),
('Destinos Turísticos Internacionais', 'Novo', 'Eliane', NULL),
('Fundamentos do Turismo e da Hospitalidade', 'Novo', 'Eliane', NULL),
('Legislação Aplicada ao Turismo', 'Novo', 'Eliane', NULL),
('Marketing Turístico', 'Novo', 'Eliane', NULL),
('Patrimônio Histórico Cultural Brasileiro', 'Novo', 'Eliane', NULL),
('Planejamento e Produção de Eventos', 'Novo', 'Eliane', NULL),
('Psicologia nas Organizações', 'Novo', 'Eliane', NULL),
('Transportes Turísticos', 'Novo', 'Eliane', NULL),
('Turismo e Sustentabilidade', 'Novo', 'Eliane', NULL),
('Gestão de Pessoas', 'Atualizar', 'Eliane', NULL),
('Google Gemini', 'Atualizando', 'Lucas', NULL),
('INTRODUÇÃO AO SERVIÇO SOCIAL', 'Atualizar', 'Eliane', NULL),
('Estética e Imagem Pessoal', 'Novo', 'Lucas', NULL),
('Barbearia', 'Novo', 'Lucas', NULL),
('Penteados e finalização', 'Novo', 'Lucas', NULL),
('Colorimetria', 'Novo', 'Lucas', NULL),
('Manicure e Pedicure', 'Novo', 'Lucas', NULL),
('Depilação', 'Novo', 'Lucas', NULL);