-- Inserir 130 novos cursos do professor Paulo Anderson
INSERT INTO public.new_courses (curso, status, professor, user_id) VALUES
('Gestão de conflitos', 'Novo', 'Paulo Anderson', NULL),
('Administração do tempo', 'Novo', 'Paulo Anderson', NULL),
('Pesquisa de clima', 'Novo', 'Paulo Anderson', NULL),
('Introdução ao pensamento de Marx', 'Novo', 'Paulo Anderson', NULL),
('Como vender pelo instagram', 'Novo', 'Paulo Anderson', NULL),
('Introdução ao pensamento filosófico', 'Novo', 'Paulo Anderson', NULL),
('Administração de condomínios', 'Novo', 'Paulo Anderson', NULL),
('Assistente contábil', 'Novo', 'Paulo Anderson', NULL),
('Assistente de PCP', 'Novo', 'Paulo Anderson', NULL),
('Auditoria empresarial', 'Novo', 'Paulo Anderson', NULL),
('Auxiliar de produção', 'Novo', 'Paulo Anderson', NULL),
('Gestão de hotéis e pousadas', 'Novo', 'Paulo Anderson', NULL),
('Síndico profissional', 'Novo', 'Paulo Anderson', NULL),
('Formação em filosofia', 'Novo', 'Paulo Anderson', NULL),
('Metodologia do trabalho científico', 'Novo', 'Paulo Anderson', NULL),
('Tecnologia e educação', 'Novo', 'Paulo Anderson', NULL),
('Política e gestão educacional', 'Novo', 'Paulo Anderson', NULL),
('Formação docente no contexto do capitalismo contemporâneo', 'Novo', 'Paulo Anderson', NULL),
('Didática, saberes docentes e práticas pedagógicas', 'Novo', 'Paulo Anderson', NULL),
('Planejamento e avaliação de sistemas educacionais', 'Novo', 'Paulo Anderson', NULL),
('Formação de monitores escolares', 'Novo', 'Paulo Anderson', NULL),
('Gestão e administração escolar', 'Novo', 'Paulo Anderson', NULL),
('Coordenação pedagógica e supervisão escolar', 'Novo', 'Paulo Anderson', NULL),
('Curso pedagogia da autonomia', 'Novo', 'Paulo Anderson', NULL),
('Formação de novos professores', 'Novo', 'Paulo Anderson', NULL),
('Recursos Humanos', 'Novo', 'Paulo Anderson', NULL),
('Liderança de alta performance', 'Novo', 'Paulo Anderson', NULL),
('Contratação de pessoas com deficiência e gestão inclusiva', 'Novo', 'Paulo Anderson', NULL),
('Formação em gestão de pessoas', 'Novo', 'Paulo Anderson', NULL),
('Assistente de recursos humanos', 'Novo', 'Paulo Anderson', NULL),
('Saúde e segurança no trabalho', 'Novo', 'Paulo Anderson', NULL),
('Consultoria em Recursos humanos', 'Novo', 'Paulo Anderson', NULL),
('Fundamentos do people analytics', 'Novo', 'Paulo Anderson', NULL),
('Aquisição de talentos', 'Novo', 'Paulo Anderson', NULL),
('Desenvolvimento de talentos', 'Novo', 'Paulo Anderson', NULL),
('Gestão de talentos', 'Novo', 'Paulo Anderson', NULL),
('RH ágil', 'Novo', 'Paulo Anderson', NULL),
('Negociação salarial', 'Novo', 'Paulo Anderson', NULL),
('Aprendizagem e desenvolvimento corporativo', 'Novo', 'Paulo Anderson', NULL),
('Treinamento de gerente', 'Novo', 'Paulo Anderson', NULL),
('Acolhimento familiar e institucional', 'Novo', 'Paulo Anderson', NULL),
('Ética e cidadania', 'Novo', 'Paulo Anderson', NULL),
('Direito da infância e juventude', 'Novo', 'Paulo Anderson', NULL),
('Cultura índigena', 'Novo', 'Paulo Anderson', NULL),
('Políticas públicas', 'Novo', 'Paulo Anderson', NULL),
('Diversidade, minoria e inclusão', 'Novo', 'Paulo Anderson', NULL),
('Vendas', 'Novo', 'Paulo Anderson', NULL),
('Gestão estratégica de preços', 'Novo', 'Paulo Anderson', NULL),
('Vendedor profissional', 'Novo', 'Paulo Anderson', NULL),
('Inteligência em vendas', 'Novo', 'Paulo Anderson', NULL),
('Expert em televendas', 'Novo', 'Paulo Anderson', NULL),
('Curso completo de neurovendas', 'Novo', 'Paulo Anderson', NULL),
('Trade marketing', 'Novo', 'Paulo Anderson', NULL),
('Curso de Copywriting', 'Novo', 'Paulo Anderson', NULL),
('Inteligência emocional no atendimento ao cliente', 'Novo', 'Paulo Anderson', NULL),
('Curso completo de neuromarketing', 'Novo', 'Paulo Anderson', NULL),
('Administração da força de vendas', 'Novo', 'Paulo Anderson', NULL),
('Gestão da inovação em startups', 'Novo', 'Paulo Anderson', NULL),
('Gestão ágil de projetos e processos', 'Novo', 'Paulo Anderson', NULL),
('Gestão de negócios na era digital', 'Novo', 'Paulo Anderson', NULL),
('Transformação digital para executivos', 'Novo', 'Paulo Anderson', NULL),
('Gestão de conflitos e mediação empresarial', 'Novo', 'Paulo Anderson', NULL),
('Gestão de pessoas com Inteligência artificial', 'Novo', 'Paulo Anderson', NULL),
('Gestão da cultura organizacional em tempos de mudança', 'Novo', 'Paulo Anderson', NULL),
('Gestão de produtos e serviços inovadores', 'Novo', 'Paulo Anderson', NULL),
('Gestão de projetos criativos e inovadores', 'Novo', 'Paulo Anderson', NULL),
('Gestão de clientes com tecnologias emergentes', 'Novo', 'Paulo Anderson', NULL),
('Negociação empresarial e gestão de stakeholders', 'Novo', 'Paulo Anderson', NULL),
('Liderança empática e gestão de equipes remotas', 'Novo', 'Paulo Anderson', NULL),
('Análise de dados para tomada de decisões empresariais', 'Novo', 'Paulo Anderson', NULL),
('Gestão da diversidade e inclusão nas organizações', 'Novo', 'Paulo Anderson', NULL),
('Gestão de eventos corporativos e marketing experencial', 'Novo', 'Paulo Anderson', NULL),
('Gestão de mídias sociais para empresas', 'Novo', 'Paulo Anderson', NULL),
('Gestão do conhecimento e inteligência organizacional', 'Novo', 'Paulo Anderson', NULL),
('Gestão da liderança positiva e bem-estar corporativo', 'Novo', 'Paulo Anderson', NULL),
('Gestão de vendas em ambientes digitais', 'Novo', 'Paulo Anderson', NULL),
('Gestão do tempo e produtividade no ambiente corporativo', 'Novo', 'Paulo Anderson', NULL),
('Gestão da transformação organizacional', 'Novo', 'Paulo Anderson', NULL),
('Gestão de talentos em organizações de alta performance', 'Novo', 'Paulo Anderson', NULL),
('Gestão da experiência do cliente', 'Novo', 'Paulo Anderson', NULL),
('Gestão de talentos em ambientes de trabalho híbridos', 'Novo', 'Paulo Anderson', NULL),
('Diversidade e inclusão em equipes multigeracionais', 'Novo', 'Paulo Anderson', NULL),
('Gestão do bem-estar psicológico no ambiente corporativo', 'Novo', 'Paulo Anderson', NULL),
('Gamificação no recrutamento e retenção de talentos', 'Novo', 'Paulo Anderson', NULL),
('Desenvolvimento de soft skills com tecnologias de realidade virtual', 'Novo', 'Paulo Anderson', NULL),
('Mindfulness e gestão do stress no ambiente de trabalho', 'Novo', 'Paulo Anderson', NULL),
('Liderança inclusiva e equipes diversas', 'Novo', 'Paulo Anderson', NULL),
('Gestão de performance e feedback em tempo real', 'Novo', 'Paulo Anderson', NULL),
('Gestão de equipes remotas com inteligência emocional', 'Novo', 'Paulo Anderson', NULL),
('Tecnologias emergentes no recursos humanos', 'Novo', 'Paulo Anderson', NULL),
('Programas de Onboarding virtual e acompanhamento de novos colaboradores', 'Novo', 'Paulo Anderson', NULL),
('Gestão de benefícios corporativos personalizados', 'Novo', 'Paulo Anderson', NULL),
('Avaliação de desempenho baseada em dados comportamentais', 'Novo', 'Paulo Anderson', NULL),
('Gestão de colaboradores freelancers e contratados', 'Novo', 'Paulo Anderson', NULL),
('Educação corporativa com microlearning', 'Novo', 'Paulo Anderson', NULL),
('Gestão de equipes de alto desempenho com base na psicologia positiva', 'Novo', 'Paulo Anderson', NULL),
('Liderança digital e a gestão de equipes virtuais', 'Novo', 'Paulo Anderson', NULL),
('Programas de recompensas e reconhecimento', 'Novo', 'Paulo Anderson', NULL),
('Programas de desenvolvimento de lideranças', 'Novo', 'Paulo Anderson', NULL),
('Engajamento e retenção de colaboradores da geração Z', 'Novo', 'Paulo Anderson', NULL),
('Educação híbrida - Como integrar o ensino presencial e online', 'Novo', 'Paulo Anderson', NULL),
('Metodologias ativas na educação infantil', 'Novo', 'Paulo Anderson', NULL),
('Gamificação no ensino superior', 'Novo', 'Paulo Anderson', NULL),
('Educação socioemocional em ambientes escolares', 'Novo', 'Paulo Anderson', NULL),
('Aprendizagem baseada em projetos no ensino fundamental', 'Novo', 'Paulo Anderson', NULL),
('Mindfulness e bem-estar no ensino', 'Novo', 'Paulo Anderson', NULL),
('Ensino por competências no ensino médio', 'Novo', 'Paulo Anderson', NULL),
('Liderança educacional no ensino superior', 'Novo', 'Paulo Anderson', NULL),
('Tecnologias emergentes na educação de jovens e adultos', 'Novo', 'Paulo Anderson', NULL),
('Desing instrucional para cursos online', 'Novo', 'Paulo Anderson', NULL),
('Escrita criativa no ensino fundamental e médio', 'Novo', 'Paulo Anderson', NULL),
('Metodolodias de ensino para ambientes multiculturais', 'Novo', 'Paulo Anderson', NULL),
('Aprendizagem criativa e inovadora no ensino médio', 'Novo', 'Paulo Anderson', NULL),
('Educação para o pensamento crítico e solução de problemas', 'Novo', 'Paulo Anderson', NULL),
('Tecnologias digitais para a gestão educacional', 'Novo', 'Paulo Anderson', NULL),
('Educação e liderança: Desenvolvendo líderes na sala de aula', 'Novo', 'Paulo Anderson', NULL),
('Cultura digital na educação', 'Novo', 'Paulo Anderson', NULL),
('Criatividade e inovação no ensino', 'Novo', 'Paulo Anderson', NULL),
('Criando ambientes de aprendizagem positiva e motivacional', 'Novo', 'Paulo Anderson', NULL),
('Psicologia e inteligência artificial: Implicações éticas', 'Novo', 'Paulo Anderson', NULL),
('Psicologia do luto digital', 'Novo', 'Paulo Anderson', NULL),
('Psicologia da personalidade no contexto profissional', 'Novo', 'Paulo Anderson', NULL),
('Psicologia do medo: tratamentos e intervenções', 'Novo', 'Paulo Anderson', NULL),
('Psicologia positiva na educação', 'Novo', 'Paulo Anderson', NULL),
('Psicologia do transtorno de estresse pós-traumático', 'Novo', 'Paulo Anderson', NULL),
('Psicologia da criatividade', 'Novo', 'Paulo Anderson', NULL),
('Psicologia e sexualidade: Terapias para distúrbios sexuais', 'Novo', 'Paulo Anderson', NULL),
('Psicologia do transtorno de ansiedade social', 'Novo', 'Paulo Anderson', NULL),
('Psicologia das relações sociais no ambiente de trabalho', 'Novo', 'Paulo Anderson', NULL),
('Transtorno obsessivo-compulsivo e novas abordagens teraupêuticas', 'Novo', 'Paulo Anderson', NULL);